<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Platforms>AnyCPU;x64;x86</Platforms>
    <ApplicationIcon>Properties\Icons\re_stickit.ico</ApplicationIcon>
    <PackageIcon>re_stickit-icon.jpg</PackageIcon>
    <SignAssembly>False</SignAssembly>
    <AssemblyVersion>3.6.0</AssemblyVersion>
    <FileVersion>3.6.0</FileVersion>
    <Title>Re_Stick-It</Title>
    <Company>969 Studios</Company>
    <Product>Re_Stick-It</Product>
    <Copyright>Copyright (c) 969 Studios</Copyright>
    <PackageProjectUrl>https://github.com/typO969/Re_Stick-It</PackageProjectUrl>
    <RepositoryUrl>https://github.com/typO969/Re_Stick-It</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <AssemblyTitle>re_Stick-It</AssemblyTitle>
    <Authors>969 Design</Authors>
    <Description>Real. Digital. Notes.</Description>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="prefs2ThinkAbout__gather-red.png" />
    <None Remove="Properties\Images\about-pin-image.png" />
    <None Remove="stickit_prefsIdeas.pdf" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Properties\Fonts\*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Properties\Icons\re_stickit.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Properties\Images\about-pin-image.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>
  <ItemGroup>
    <None Update="Properties\Icons\re_stickit-icon.jpg">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>






</Project>
